
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets MUST NOT fallback
    location /static/ {
        try_files $uri =404;
        access_log off;
        expires 1y;
    }

    location = /manifest.json {
        try_files $uri =404;
    }

    location = /favicon.ico {
        try_files $uri =404;
    }
}
