apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: travelmemory
spec: 
  replicas: 1
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: backend-container
        image: saiyedin786/capstone:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3001


