apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: travelmemory
spec: 
  replicas: 1
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: saiyedin786/capstone:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

